# Calamares configuration for CODER-OS
---
modules-search: [ local ]

instances:
  - id:       coder_postinstall
    module:   shellprocess
    config:   shellprocess.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - bootloader
      - shellprocess@coder_postinstall
      - umount
  - show:
      - finished

branding: coderos
prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
